# NumPy 


O NumPy é uma Biblioteca de Álgebra Linear para Python, o motivo pelo qual é tão importante para a Ciência de Dados com Python é que quase todas as bibliotecas do Ecossistema PyData confiam no NumPy como um de seus principais blocos de construção.

O Numpy também é rápido, pois possui ligações para as bibliotecas C. Para obter mais informações sobre por que você gostaria de usar matrizes em vez de listas, confira em [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

## Instruções de instalação

** É altamente recomendável instalar o Python usando a distribuição Anaconda para garantir que todas as dependências subjacentes (como as bibliotecas de álgebra linear) sejam sincronizadas com o uso de uma instalação conda. Se você possui o Anaconda, instale o NumPy acessando o terminal ou prompt de comando e digitando: **
    
    conda install numpy
    
**Se você não possui o Anaconda e não pode instalá-lo, consulte a documentação oficial do Numpy em várias instruções de instalação.(http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Usando NumPy

Depois de instalar o NumPy, você pode importá-lo como uma biblioteca:

In [3]:
import numpy as np

O Numpy possui muitas funções e recursos internos. Não abordaremos todos eles, mas focaremos alguns dos aspectos mais importantes do Numpy: vetores, matrizes, matrizes e geração de números. Vamos começar discutindo matrizes.

# Numpy Arrays

As matrizes NumPy são a principal maneira de usarmos o Numpy ao longo do curso. Matrizes numpy vêm basicamente em dois sabores: vetores e matrizes. Os vetores são estritamente matrizes 1-d e matrizes são 2-d (mas você deve observar que uma matriz ainda pode ter apenas uma linha ou uma coluna).

Vamos começar nossa introdução explorando como criar matrizes NumPy.

## Criando matrizes NumPy

### De uma lista Python

Podemos criar uma matriz convertendo diretamente uma lista ou lista de listas:

In [4]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Métodos internos

Existem várias maneiras internas de gerar matrizes


### arange

Retorne valores espaçados uniformemente dentro de um determinado intervalo.

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])


### zeros e uns

Gere matrizes de zeros ou uns

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace

Retornar números espaçados uniformemente em um intervalo especificado.

In [15]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [16]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye


Cria uma matriz de identidade

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

O Numpy também tem várias maneiras de criar matrizes de números aleatórios:

### rand
Crie uma matriz da forma especificada e preencha-a com
amostras aleatórias de uma distribuição uniforme
sobre `` [0, 1) ``.

In [18]:
np.random.rand(2)

array([0.0263219 , 0.15528661])

In [19]:
np.random.rand(5,5)

array([[0.74869599, 0.47853638, 0.77170787, 0.84476133, 0.75465698],
       [0.77765431, 0.57186754, 0.2663578 , 0.96615149, 0.20814401],
       [0.60475402, 0.46366815, 0.75539114, 0.67984809, 0.10481528],
       [0.11961977, 0.9676975 , 0.40153736, 0.53462619, 0.15398171],
       [0.96543098, 0.12064989, 0.41748531, 0.35862209, 0.70116806]])

### randn


Retorne uma amostra (ou amostras) da distribuição "normal normal". Ao contrário do rand, que é uniforme:

In [20]:
np.random.randn(2)

array([ 0.77613964, -0.69190923])

In [21]:
np.random.randn(5,5)

array([[ 1.18472171, -0.75192084, -2.06751403,  0.13479594,  0.20674484],
       [ 1.25363249,  1.50570617, -2.19638675,  0.18502635,  0.32957489],
       [-0.7491048 , -0.30759218,  0.33963116, -0.31903437,  0.47256592],
       [-0.85998365,  0.5578632 ,  1.24108678, -2.00091047,  1.6596435 ],
       [-0.76095567,  0.40933875, -0.35611438, -1.92589344, -0.13696867]])

### randint
Retorne números inteiros aleatórios de `baixo` (inclusive) para` alto` (exclusivo).

In [22]:
np.random.randint(1,100)

38

In [23]:
np.random.randint(1,100,10)

array([78, 25, 52, 37, 95, 56, 12, 97, 36,  8])


## Atributos e métodos de matriz

Vamos discutir alguns atributos e métodos úteis ou uma matriz:

In [26]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr

array([49, 37, 29, 29, 48, 46, 27, 19, 21,  1])

## Reshape
Retorna uma matriz que contém os mesmos dados com uma nova forma.

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

Estes são métodos úteis para encontrar valores máximos ou mínimos. Ou para encontrar seus locais de índice usando argmin ou argmax

In [30]:
ranarr

array([49, 37, 29, 29, 48, 46, 27, 19, 21,  1])

In [31]:
ranarr.max()

49

In [32]:
ranarr.argmax()

0

In [33]:
ranarr.min()

1

In [34]:
ranarr.argmin()

9

## Shape

Shape is an attribute that arrays have (not a method):

In [35]:
# Vector
arr.shape

(25,)

In [36]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [37]:
arr.reshape(1,25).shape

(1, 25)

In [38]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [39]:
arr.reshape(25,1).shape

(25, 1)

### dtype


Você também pode pegar o tipo de dados do objeto na matriz:

In [40]:
arr.dtype

dtype('int64')


# Bom trabalho!